<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('sales', function (Blueprint $table) {
            $table->id();

            // NOTE - Implement foreign IDs on task 3
            // $table->foreignId('employee');

            $table->date('date_time_of_sale')->format('d/m/y');

            // CHANGE - Money should be stored as decimal.
            // $table->unsignedInteger('sale_price');
            $table->decimal('sale_price', total: 8, places: 2);

            // CHANGE - unsignedInteger() ranges from 0 to 4294967295. unsignedMediumInteger() ranges from 0 to 16777215, which seems more appropriate for product IDs, and more performant.   
            // $table->unsignedInteger('product_id');
            $table->unsignedMediumInteger('product_id');

            // CHANGE - Retained create_time and update_time columns as $table->timestamps() is generated by default, and these columns are considered best practice / potentially useful 
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('sales');
    }
};
