<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('sales', function (Blueprint $table) {
            $table->id();

            // CHANGE - This migration now utilizes foreign IDs to reflect the relationships between models
            // $table->foreignId('employee');
            $table->foreignId('employees_id')->constrained()->onDelete('cascade');
            $table->foreignId('products_id')->constrained()->onDelete('cascade');

            $table->date('date_time_of_sale')->format('d/m/y');

            // CHANGE - Money should be stored as decimal.
            // $table->unsignedInteger('sale_price');
            $table->decimal('sale_price', total: 8, places: 2);

            // CHANGE - Retained create_time and update_time columns as $table->timestamps() is generated by default, and these columns are considered best practice / potentially useful 
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('sales');
    }
};
