<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('products', function (Blueprint $table) {
            $table->id();
            $table->string('name');

            // CHANGE - Money should be stored as decimal.
            // $table->float('original_price');
            $table->decimal('original_price', total: 8, places: 2);

            // CHANGE - Money should be stored as decimal.
            // $table->float('discount_20%_when_over_price');
            $table->decimal('discount_20%_when_over_price', total: 8, places: 2);

            // CHANGE - Retained create_time and update_time columns as $table->timestamps() is generated by default, and these columns are considered best practice / potentially useful 
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('products');
    }
};
